ALTER TABLE cidade DROP COLUMN nome_estado;
ALTER TABLE cidade ADD COLUMN estado_id BIGINT NOT NULL;
ALTER TABLE cidade ADD CONSTRAINT fk_estado FOREIGN KEY (estado_id) REFERENCES estado (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE cidade RENAME COLUMN nome_cidade TO nome;