
CREATE SEQUENCE seq_cidade START 1 INCREMENT 1;
CREATE SEQUENCE seq_cozinha START 1 INCREMENT 1;
CREATE SEQUENCE seq_estado START 1 INCREMENT 1;
CREATE SEQUENCE seq_forma_pagamento START 1 INCREMENT 1;
CREATE SEQUENCE seq_grupo START 1 INCREMENT 1;
CREATE SEQUENCE seq_permissao START 1 INCREMENT 1;
CREATE SEQUENCE seq_produto START 1 INCREMENT 1;
CREATE SEQUENCE seq_restaurante START 1 INCREMENT 1;
CREATE SEQUENCE seq_usuario START 1 INCREMENT 1;


CREATE TABLE estado (
	id BIGINT NOT NULL PRIMARY KEY, 
	nome VARCHAR(255) NOT NULL
);

CREATE TABLE cidade (
	id BIGINT NOT NULL PRIMARY KEY, 
	nome VARCHAR(255) NOT NULL, 
	estado_id BIGINT NOT NULL REFERENCES estado(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE cozinha (
    id BIGINT NOT NULL PRIMARY KEY, 
    nome VARCHAR(255) NOT NULL, 
    estado_id BIGINT REFERENCES estado (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE forma_pagamento (
  id BIGINT NOT NULL PRIMARY KEY, 
  descricao VARCHAR(255)
);

CREATE TABLE grupo (
  id BIGINT NOT NULL PRIMARY KEY,
  nome VARCHAR(255)
);

CREATE TABLE permissao (
  id BIGINT NOT NULL PRIMARY KEY, 
  descricao VARCHAR(255), 
  nome VARCHAR(255) NOT NULL
);

CREATE TABLE grupo_permissao (
  grupo_id BIGINT NOT NULL REFERENCES grupo  (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  permissao_id BIGINT NOT NULL REFERENCES permissao (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE restaurante (
  id BIGINT NOT NULL PRIMARY KEY, 
  data_atualizacao TIMESTAMP NOT NULL, 
  data_cadastro TIMESTAMP NOT NULL, 
  endereco_bairro VARCHAR(255), 
  endereco_cep VARCHAR(255), 
  endereco_complemento VARCHAR(255), 
  endereco_logradouro VARCHAR(255), 
  endereco_numero VARCHAR(255), 
  nome VARCHAR(255) NOT NULL, 
  taxa_frete NUMERIC(19, 2) NOT NULL, 
  cozinha_id BIGINT NOT NULL REFERENCES cozinha (id) ON UPDATE NO ACTION ON DELETE NO ACTION, 
  endereco_cidade_id BIGINT REFERENCES cidade (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE produto (
  id BIGINT NOT NULL PRIMARY KEY, 
  ativo BOOLEAN, 
  descricao VARCHAR(255), 
  nome VARCHAR(255), 
  preco NUMERIC(19, 2), 
  restaurante_id BIGINT REFERENCES restaurante (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);


CREATE TABLE restaurante_forma_pagamento (
  restaurante_id BIGINT NOT NULL REFERENCES restaurante (id) ON UPDATE NO ACTION ON DELETE NO ACTION, 
  forma_pagamento_id BIGINT NOT NULL REFERENCES forma_pagamento (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE usuario (
  id BIGINT NOT NULL PRIMARY KEY, 
  data_cadastro TIMESTAMP NOT NULL, 
  email VARCHAR(255), 
  nome VARCHAR(255), 
  senha VARCHAR(255)
);

CREATE TABLE usuario_grupo (
  usuario_id BIGINT NOT NULL REFERENCES usuario (id) ON UPDATE NO ACTION ON DELETE NO ACTION, 
  grupo_id BIGINT NOT NULL  REFERENCES grupo (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);
